---
- name: Setup repository
  ansible.builtin.yum_repository:
    async: "{{ item.async | default(omit) }}"
    attributes: "{{ item.attributes | default(omit) }}"
    bandwidth: "{{ item.bandwidth | default(omit) }}"
    baseurl: "{{ item.baseurl | default(omit) }}"
    cost: "{{ item.cost | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    enabled: "{{ item.enabled | default(omit) }}"
    enablegroups: "{{ item.enablegroups | default(omit) }}"
    exclude: "{{ item.exclude | default(omit) }}"
    failovermethod: "{{ item.failovermethod | default(omit) }}"
    file: "{{ item.file | default(omit) }}"
    gpgcakey: "{{ item.gpgcakey | default(omit) }}"
    gpgcheck: "{{ item.gpgcheck | default(omit) }}"
    gpgkey: "{{ item.gpgkey | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    include: "{{ item.include | default(omit) }}"
    includepkgs: "{{ item.includepkgs | default(omit) }}"
    keepalive: "{{ item.keepalive | default(omit) }}"
    keepcache: "{{ item.keepcache | default(omit) }}"
    metalink: "{{ item.metalink | default(omit) }}"
    mirrorlist: "{{ item.mirrorlist | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    name: "{{ item.name }}"
    owner: "{{ item.owner | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    priority: "{{ item.priority | default(omit) }}"
    protect: "{{ item.protect | default(omit) }}"
    proxy: "{{ item.proxy | default(omit) }}"
    reposdir: "{{ item.reposdir | default(omit) }}"
    retries: "{{ item.retries | default(omit) }}"
    selevel: "{{ item.selevel | default(omit) }}"
    serole: "{{ item.serole | default(omit) }}"
    setype: "{{ item.setype | default(omit) }}"
    seuser: "{{ item.seuser | default(omit) }}"
    sslcacert: "{{ item.sslcacert | default(omit) }}"
    sslclientcert: "{{ item.sslclientcert | default(omit) }}"
    sslclientkey: "{{ item.sslclientkey | default(omit) }}"
    sslverify: "{{ item.sslverify | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    throttle: "{{ item.throttle | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    username: "{{ item.username | default(omit) }}"
    repo: "{{ item.repo | default(omit) }}"
