name: CI
on: [push]
jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: python3 -m pip install --user ansible-lint

      - name: Lint
        run: ansible-lint .

  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian10
          - debian11
          - debian12
          - fedora38
          - rockylinux8
          - rockylinux9
          - ubuntu1804
          - ubuntu2004
          - ubuntu2204

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: python3 -m pip install --user ansible molecule molecule-plugins[docker] docker

      - name: Run Molecule
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy
        run: >-
          ansible-galaxy role import --token ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
